# Generated by Django 6.0.3 on 2026-04-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_fix_avatar_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
